---
- name: Configure Jellyfin ports
  xml:
    path: /etc/jellyfin/system.xml
    xpath: /ServerConfiguration/{{ item.key }}
    value: "{{ item.value }}"
  loop:
    - key: PublicPort
      value: "{{ jellyfin_HTTP_port }}"
    - key: PublicHttpsPort
      value: "{{ jellyfin_HTTPS_port }}"
    - key: HttpServerPortNumber
      value: "{{ jellyfin_HTTP_port }}"
    - key: HttpsPortNumber
      value: "{{ jellyfin_HTTPS_port }}"
  notify: Restart Jellyfin
...
