---
platforms:
  - name: debian-stretch
    image: minimum2scp/systemd-stretch
    privileged: true
    command: /sbin/init
    published_ports:
      - "80"
      - "443"
      - "8096"
      - "8920"

  - name: debian-buster
    image: minimum2scp/systemd-buster
    privileged: true
    command: /sbin/init
    published_ports:
      - "80"
      - "443"
      - "8096"
      - "8920"

  - name: ubuntu-bionic
    image: jrei/systemd-ubuntu:18.04
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - "80"
      - "443"
      - "8096"
      - "8920"

verifier:
  name: testinfra
...
